language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

install: true
script:
  - ./gradlew clean jbake	

after_success:
    #clone `master' branch of the repository using encrypted GH_TOKEN for authentification
  - git clone https://${GH_TOKEN}@github.com/tastybooks/tastybooks.github.io.git ../tastybooks.github.io.master

    # copy generated HTML site to `master' branch
  - cp -R build/jbake/* ../tastybooks.github.io.master
    # commit and push generated content to `master' branch
    # since repository was cloned in write mode with token auth - we can push there
  - cd ../tastybooks.github.io.master
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add -A . 
  - git commit -m "Deploy to GitHub Pages ${TRAVIS_BUILD_NUMBER}"
  #- git commit -m "Deploy to GitHub Pages"
  - git push --quiet origin master > /dev/null 2>&1

branches:
  only:
  - source

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - golodnyj@gmail.com
    on_success: always

